CREATE DATABASE IF NOT EXISTS
    NorkTown;
USE NorkTown;

CREATE TABLE IF NOT EXISTS cars (
    id INT(11) AUTO_INCREMENT,
    colors VARCHAR(255),
    models VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO cars VALUE (0, 0, 0);
INSERT INTO cars VALUE (0, 0, 0);
INSERT INTO cars VALUE (0, 0, 0);

