version: "3.1"

services:
  db:
    container_name: pg_banco_carros
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: carros_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carros.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"